Document: python-systemd-cython
Title: Debian python-systemd-cython Manual
Author: <insert document author here>
Abstract: This manual describes what python-systemd-cython is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-systemd-cython/python-systemd-cython.sgml.gz

Format: postscript
Files: /usr/share/doc/python-systemd-cython/python-systemd-cython.ps.gz

Format: text
Files: /usr/share/doc/python-systemd-cython/python-systemd-cython.text.gz

Format: HTML
Index: /usr/share/doc/python-systemd-cython/html/index.html
Files: /usr/share/doc/python-systemd-cython/html/*.html
